### ISSUE TITLE
Not working with Android Q

### ISSUE THREAD

**Issue by puneetbahuguna** [yuger/VPN_2017#21]
Hi This is not working with Android Q 10.0 . Not able to connect to VPN with android 10.0

**Comment by yuger** [comment]
https://github.com/schwabe/ics-openvpn

**Comment by puneetbahuguna** [comment]
Hi Yuger,
Implementation of this is bit different from link you shared. If you can please also add the support of android Q in your project as well. As what I understood problem could be its not reading your files from asset folder.

**Comment by puneetbahuguna** [comment]
Done.
