### ISSUE TITLE
Missing files in main\res\drawable

### ISSUE THREAD

**Issue by skumbhare** [yuger/VPN_2017#7]
While building the project, I got the following errors:
```
H:\Github\VPN_2017\vpn2017\build\intermediates\res\merged\debug\values\values.xml
Error:(636, 49) No resource found that matches the given name (at 'ic_menu_close_clear_cancel' with value '@drawable/ic_media_close_clear_cancel').
Error:(636, 49) No resource found that matches the given name (at 'ic_menu_close_clear_cancel' with value '@drawable/ic_media_close_clear_cancel').
```
Turns out that the following icon files are missing:
ic_media_close_clear_cancel
ic_media_pause
ic_media_play
ic_stat_vpn_offline
ic_stat_vpn_outline
ic_stat_vpn_empty_halo

Please include the files in `VPN_2017\vpn2017\src\main\res\drawable`.

**Comment by yuger** [comment]
Ok,  commited.
